import { useState } from 'react';
import { ArrowLeft, Copy, Download, Check, RotateCcw } from 'lucide-react';
import { ConfirmModal } from '../components/ConfirmModal';

const TEAM_EMOJI = ['🔴', '🟡', '🟢', '🔵', '🟣', '🟠', '🩵', '🩷'];
const CONFETTI_COLORS = ['#F45B69', '#F4A423', '#3BBF7A', '#4A90E2', '#9B59B6', '#FF7043'];

const CONFETTI_PIECES = Array.from({ length: 60 }, (_, i) => ({
  left: ((i * 1618) % 100),
  color: CONFETTI_COLORS[i % CONFETTI_COLORS.length],
  delay: (i * 0.045) % 1.6,
  duration: 2.2 + (i % 4) * 0.55,
  size: 6 + (i % 6) * 1.4,
  shape: i % 3,
}));

function Confetti({ show }) {
  if (!show) return null;
  return (
    <div className="fixed inset-0 pointer-events-none z-50 overflow-hidden">
      {CONFETTI_PIECES.map((p, i) => (
        <div
          key={i}
          style={{
            position: 'absolute',
            left: `${p.left}%`,
            top: '-20px',
            width: p.size,
            height: p.size,
            background: p.color,
            borderRadius: p.shape === 0 ? '50%' : p.shape === 1 ? '0' : '3px',
            animation: `confetti-fall ${p.duration}s ${p.delay}s ease-in forwards`,
          }}
        />
      ))}
    </div>
  );
}

function TeamSummaryCard({ team }) {
  return (
    <div
      className="rounded-2xl p-4"
      style={{
        background: '#FFFFFF',
        border: `1.5px solid ${team.color}55`,
      }}
    >
      <div className="flex items-center gap-2 mb-3">
        <div style={{ width: 12, height: 12, borderRadius: '50%', background: team.color, border: '2px solid #1A1A1A', flexShrink: 0 }} />
        <span style={{ fontFamily: "'Press Start 2P'", fontSize: 8, color: '#1A1A1A' }}>
          {team.teamName}
        </span>
        <span
          className="ml-auto rounded-full px-2 py-0.5 font-bold"
          style={{
            fontFamily: "'Nunito', sans-serif",
            fontWeight: 800,
            fontSize: '10px',
            background: team.lightColor || '#F4F4F6',
            color: team.color,
            border: `1px solid ${team.color}`,
          }}
        >
          {team.members.filter(Boolean).length} members
        </span>
      </div>
      <div className="flex flex-col gap-1.5">
        {team.members.filter(Boolean).map(m => {
          const dotColor = m.skill === 'Senior' ? '#3BBF7A' : m.skill === 'Mid' ? '#F4A423' : m.skill === 'Junior' ? '#F45B69' : '#BBBBBB';
          return (
            <div key={m.id} className="flex items-center gap-2">
              <div style={{ width: 7, height: 7, borderRadius: '50%', background: dotColor, border: '1px solid #1A1A1A', flexShrink: 0 }} />
              <span style={{ fontFamily: "'Nunito', sans-serif", fontWeight: 800, fontSize: '13px', color: '#1A1A1A' }}>{m.name}</span>
              {(m.skill || m.department) && (
                <span style={{ fontFamily: "'Nunito', sans-serif", fontWeight: 700, fontSize: '11px', color: '#888888' }}>
                  {[m.skill, m.department].filter(Boolean).join(' · ')}
                </span>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

export function Export({ teams, onBackToArena, onStartOver }) {
  const [copied, setCopied] = useState(false);
  const [confetti, setConfetti] = useState(true);
  const [confirm, setConfirm] = useState(null);

  if (confetti) setTimeout(() => setConfetti(false), 4500);

  function buildSlackText() {
    const lines = [
      '🎲 *Team Randomizer Results*',
      '━━━━━━━━━━━━━━━━━━━━━━',
      '',
    ];
    teams.forEach((team, i) => {
      lines.push(`${TEAM_EMOJI[i % TEAM_EMOJI.length]} *${team.teamName}*`);
      team.members.filter(Boolean).forEach(m => {
        const meta = [m.skill || 'unset', m.department].filter(Boolean).join(' · ');
        lines.push(`• ${m.name}${meta ? ` (${meta})` : ''}`);
      });
      lines.push('');
    });
    lines.push('━━━━━━━━━━━━━━━━━━━━━━');
    lines.push('Generated by Team Randomizer');
    return lines.join('\n');
  }

  function handleCopy() {
    navigator.clipboard.writeText(buildSlackText()).then(() => {
      setCopied(true);
      setConfetti(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  function handleCSV() {
    const rows = [['Team Name', 'Member Name', 'Skill Level', 'Department']];
    teams.forEach(team =>
      team.members.filter(Boolean).forEach(m =>
        rows.push([team.teamName, m.name, m.skill || '', m.department || ''])
      )
    );
    const csv = rows.map(r => r.map(c => `"${c.replace(/"/g, '""')}"`).join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `teams-${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="max-w-3xl mx-auto px-4 py-10 screen-enter">
      <Confetti show={confetti} />

      <div className="text-center mb-10">
        <h2 style={{ fontFamily: "'Press Start 2P'", fontSize: '13px', color: '#3BBF7A', marginBottom: 8 }}>
          📋 Your Teams Are Ready!
        </h2>
        <p style={{ fontFamily: "'Nunito', sans-serif", fontWeight: 700, color: '#888888', fontSize: '14px' }}>
          Drag &amp; drop is done — here&apos;s your final lineup.
        </p>
      </div>

      {/* Summary grid */}
      <div className="grid gap-3 mb-8" style={{ gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))' }}>
        {teams.map(team => (
          <TeamSummaryCard key={team.teamId} team={team} />
        ))}
      </div>

      {/* Export card */}
      <div
        className="rounded-2xl p-6 mb-6"
        style={{
          background: '#FFFFFF',
          border: '1.5px solid #D4C5B5',
        }}
      >
        <h3 style={{ fontFamily: "'Press Start 2P'", fontSize: '9px', color: '#1A1A1A', marginBottom: 16 }}>
          Export
        </h3>

        <pre
          className="rounded-xl p-4 mb-4 overflow-x-auto"
          style={{
            fontFamily: 'ui-monospace, Consolas, monospace',
            fontSize: '12px',
            lineHeight: '1.7',
            background: '#F7F0E8',
            color: '#555555',
            border: '1px solid #D4C5B5',
            whiteSpace: 'pre-wrap',
          }}
        >
          {buildSlackText()}
        </pre>

        <div className="flex gap-3 flex-wrap">
          <button
            onClick={handleCopy}
            className="btn-press flex items-center gap-2 rounded-xl px-5 py-3 font-bold"
            style={{
              fontFamily: "'Nunito', sans-serif",
              fontWeight: 800,
              fontSize: 13,
              background: copied ? '#E8F8F1' : '#F7F0E8',
              color: copied ? '#2E9E5E' : '#555555',
              border: `1.5px solid ${copied ? '#3BBF7A' : '#1A1A1A'}`,
              boxShadow: `2px 2px 0 ${copied ? '#3BBF7A' : '#1A1A1A'}`,
            }}
          >
            {copied ? <Check size={14} /> : <Copy size={14} />}
            {copied ? '✅ Copied!' : 'Copy for Slack'}
          </button>

          <button
            onClick={handleCSV}
            className="btn-press flex items-center gap-2 rounded-xl px-5 py-3 font-bold"
            style={{
              fontFamily: "'Nunito', sans-serif",
              fontWeight: 800,
              fontSize: 13,
              background: '#F7F0E8',
              color: '#555555',
              border: '1.5px solid #1A1A1A',
              boxShadow: '2px 2px 0 #1A1A1A',
            }}
          >
            <Download size={14} /> Download CSV
          </button>
        </div>
      </div>

      <div className="flex gap-3 justify-center">
        <button
          onClick={onBackToArena}
          className="btn-press flex items-center gap-2 rounded-xl px-5 py-3 font-bold"
          style={{
            fontFamily: "'Nunito', sans-serif",
            fontWeight: 800,
            fontSize: 13,
            background: '#FFFFFF',
            color: '#555555',
            border: '2px solid #1A1A1A',
            boxShadow: '3px 3px 0 #1A1A1A',
          }}
        >
          <ArrowLeft size={14} /> Back to Arena
        </button>

        <button
          onClick={() => setConfirm({ message: 'Start over? All team data will be lost.', onConfirm: onStartOver })}
          className="btn-press flex items-center gap-2 rounded-xl px-5 py-3 font-bold"
          style={{
            fontFamily: "'Nunito', sans-serif",
            fontWeight: 800,
            fontSize: 13,
            background: '#FEE8EA',
            color: '#F45B69',
            border: '2px solid #1A1A1A',
            boxShadow: '3px 3px 0 #1A1A1A',
          }}
        >
          <RotateCcw size={14} /> Start Over
        </button>
      </div>

      {confirm && (
        <ConfirmModal
          message={confirm.message}
          onConfirm={confirm.onConfirm}
          onCancel={() => setConfirm(null)}
        />
      )}
    </div>
  );
}
